services:
  # Serviço PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # Persistência dos dados do banco
      - postgres_data:/var/lib/postgresq
      # Não incluiu a política de restart: always

  # Serviço pgAdmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    links:
      # Permite que o pgAdmin se comunique com o container do Postgres
      - postgres
    depends_on:
      - postgres
      # Não incluiu a política de restart: always

volumes:
  # Volume para garantir que os dados do Postgres persistam
  postgres_data: